name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: setup node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: lts/*
          cache: pnpm

      - name: install
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: lint
        run: pnpm lint

      - name: typecheck
        run: pnpm typecheck

  test:
    name: "test (os: ${{ matrix.os }}, node: ${{ matrix.node }}, vitest: ${{ matrix.vitest }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [20, 22, 24]
        vitest: [3.0.0, 3.2.4, latest]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: setup node ${{ matrix.node }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: install
        run: pnpm install --frozen-lockfile

      - name: install vitest ${{ matrix.vitest }}
        run: pnpm add -D vitest@${{ matrix.vitest }}

      - name: test
        if: matrix.os != 'ubuntu-latest' && matrix.node != 22 && matrix.vitest != 'latest'
        run: pnpm test

      - name: test with coverage
        if: matrix.os == 'ubuntu-latest' || matrix.node == 22 || matrix.vitest == 'latest'
        run: pnpm test --coverage

      - name: upload coverage reports to codecov
        if: matrix.os == 'ubuntu-latest' || matrix.node == 22 || matrix.vitest == 'latest'
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
