name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: install pnpm
        uses: pnpm/action-setup@v4

      - name: seyup node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: lts/*

      - name: install
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: lint
        run: pnpm lint

      - name: typecheck
        run: pnpm typecheck

  test:
    name: "test (os: ${{ matrix.os }}, node: ${{ matrix.node }}, vitest: ${{ matrix.vitest }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [22, 20, 18]
        vitest:
          - latest
          - 2.0.0
          - 1.6.0
          - 1.5.3
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@v4.2.2

      - name: install pnpm
        uses: pnpm/action-setup@v4

      - name: setup node ${{ matrix.node }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node }}

      - name: install
        run: pnpm install --frozen-lockfile

      - name: install Vitest
        run: pnpm add -D vitest@${{ matrix.vitest }}

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test
